#!/usr/bin/env bash
# Terminate SSL on HAproxy

sudo /opt/certbot/bin/pip install certbot certbot-nginx
sudo certbot certonly --standalone -d dig 54.210.47.110
listen on TCP 443
sudo service haproxy restart
