#!/usr/bin/env bash
# Bash script that configures a server
if ! command -v nginx &> /dev/null; then
	exit 1
fi
if ! pgrep nginx &> /dev/null; then
	sudo systemctl start nginx
fi
if ! sudo nginx -t &> /dev/null; then
	exit 1
fi
if ! grep -q "listen 80;" /etc/nginx/nginx.conf; then
	sudo sed -i 's/listen\s\+80\s*;/listen 80;/g' /etc/nginx/nginx.conf
fi
if sudo lsof -i :80 &> /dev/null; then
	exit 1
fi
sudo systemctl restart nginx
response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost)
if [[ $response_code == 200 ]]; then
	cat << EOF 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
EOF
fi
