#!/usr/bin/env bash
# Bash script that configures a server
if ! command -v nginx &> /dev/null; then
	exit 1
fi
if ! pgrep nginx &> /dev/null; then
	sudo systemctl start nginx
fi
if ! sudo nginx -t &> /dev/null; then
	exit 1
fi
if ! grep -q "listen 80;" /etc/nginx/nginx.conf; then
	sudo sed -i 's/listen\s\+80\s*;/listen 80;/g' /etc/nginx/nginx.conf
fi
if sudo lsof -i :80 &> /dev/null; then
	exit 1
fi
sudo systemctl restart nginx
