#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but "Hi" in line 9
count=1

while [ $count -le 10 ];
do
	echo "Best School"
	let count=count+1
	if [ $count -e 9 ];
	then
		echo "Hi"
	fi
done
