#!/usr/bin/env bash
#Displays numbers 1 to 20 with strings inbetween.
count=1

while [ $count -le 20 ];
do
	echo $count
	case $count in
	4)
	echo "bad luck from China";;
	case $count in
	9)
	echo "bad luck from Japan";;
	case $count in
	17)
	echo "bad luck from Italy";;
	let count=count+1
done
