#!/usr/bin/env bash
#Displays "bad luck" at line 4 and "good luck" at line 8,the rest "Best School"
count=1

while [ $count -le 20 ];
do
	echo $count
	case $count in
	4)
	echo "bad luck from China";;
	case $count in
	9)
	echo "bad luck from Japan";;
	case $count in
	17)
	echo "bad luck from Italy";;
	let count=count+1
done
