#!/usr/bin/env bash
#Displays hours of the clock and minutes between them
count=-1
minutes=1
while [ "$count" -lt 12 ];
do
	count=$(( count + 1 ))
	echo "Hour: "$count""
	while [ $minutes -le 59 ];
	do
		echo "$minutes"
		minutes=$(( minutes + 1 ))
	done
	minutes=1
done
