#!/usr/bin/env bash
#Script checks if files exist or not, empty or not and if they are regular.

if [ -e school ];
then
	echo "school file exists"
	if [ -s school ];
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
		if [ -f school ];
		then
			echo "school is a regular file"
		fi
	fi
else
	echo "school file does not exist"
fi
